### ISSUE TITLE
Create DBInstance

### ISSUE THREAD

**Issue by wpmoore2** [ACM-NCSU/ACM-AITP-CoursePro#10]
**As a developer** I need to have a DBInstance.java class which will wrap the SqlJetDb object.  Being this is the initial setup of the database, the SqlJet jar file will need to be added to the project build path.

A java class DBInstance shall be made under the data/ folder which, it can initialize a usable SqlJetDb instance.

### Definition of Done:
*  Project builds with SqlJet
*  New DBInstance class is made

### Acceptance Criteria:
* Basic unit tests which show that the DBInstance can be made and used.

**Comment by mattgd** [comment]
@wpmoore2 Before adding in SqlJet, should we setup some sort of dependency management for the project (e.g. Maven, Gradle, Ant)? This would be great for an automated CI and CD pipeline, but it could also add a bit of additional overhead for new contributors setting up their environment.

**Comment by wpmoore2** [comment]
Left from Java Implementation - invalid.
