### ISSUE TITLE
Create DBManager

### ISSUE THREAD

**Issue by wpmoore2** [ACM-NCSU/ACM-AITP-CoursePro#11]
**As a developer** I need to create the DBManager class which will orchestrate use of the DBInstances.  SqlJet uses a .db file to manage storage; this class should initialize a root DB from a root file which has a table of user information.

The class should find the root .db file, or create a new one if none exists.  The new file will add a new user data table, as defined by the DATABASE_SCHEMA.
* If there is no link to the DB schema, then it has not been updated yet.  This issue is BLOCKED.

### Definition of Done:
*  A DBManager class is created under folder /lib
* The class creates/loads a root DB when constructed

**Comment by mattgd** [comment]
Added [on hold](https://github.com/ACM-NCSU/ACM-AITP-CoursePro/labels/on%20hold) label. Dependent on the completion of #13.

**Comment by wpmoore2** [comment]
Left from Java Implementation - invalid.
