### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by mattgd** [ACM-NCSU/ACM-AITP-CoursePro#14]
## Feature Description/Use
In the interest of open source best practices, a license file (`LICENSE.md`) should be added that complies with our interests as well as our dependencies. To my knowledge, we'll need something that is GNU GPL compliant since SQLJet, one of our planned dependencies, is under GNU GPL ([read more](https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL)).

## General Changes Required
* Pick an appropriate GNU *GPL license ([a few options](https://choosealicense.com/licenses/))
  - I'm all for the less strict licenses for a project like this (GPLv3 or LGPLv3), but please let me know your thoughts.
* Create a `LICENSE.md` file in the root directory of the repository

**Comment by wpmoore2** [comment]
MIT License included. Can revisit later if amendments are needed.
