### ISSUE TITLE
Create Event

### ISSUE THREAD

**Issue by mattgd** [ACM-NCSU/ACM-AITP-CoursePro#15]
As a **developer** I need a designated class for an Event in CoursePro. The `Event` class will be an abstract parent class of the `Course` and `Assignment` classes, and will hold the following fields:
* Name (A `String` that cannot be null or empty)
* Description (A `String`)
* Date/time (`java.util.Date` instance, cannot be null)
* Repeat (A `long` value, representing repeat interval in seconds)
* Location (A `Location` instance, see #18)

## Definition of Done:

The `Event` class exists with the specifications listed above (or modified functionality discussed in subsequent comments below), and can be extended for use with other child classes.

## Acceptance Criteria:

The application can be started as before, and the `Event` class has no compilation errors and passes all developer-defined unit tests, which provide full line coverage for the `Event` class' methods.

**Comment by wpmoore2** [comment]
Left from Java Implementation - invalid.
