### ISSUE TITLE
Create Course

### ISSUE THREAD

**Issue by mattgd** [ACM-NCSU/ACM-AITP-CoursePro#16]
As a **developer** I need a designated class for a Course in CoursePro. The Course class will be a child of the Event class (see #15), and will hold the following fields:
* Syllabus (A _File_ instance, which will be saved in the local storage)
* A List/Map of `Event` objects (consider LinkedList or HashMap)
* A List of `Note` objects (consider ArrayList or LinkedList)

## Definition of Done:

The `Course` class exists with the specifications listed above (or modified functionality discussed in subsequent comments below).

## Acceptance Criteria:

The application can be started as before, and the `Course` class has no compilation errors and passes all developer-defined unit tests, which provide full line coverage for the `Course` class' methods.

**Comment by wpmoore2** [comment]
Left from java implementation - maybe valid later but closing for now
