### ISSUE TITLE
Create Assignment

### ISSUE THREAD

**Issue by mattgd** [ACM-NCSU/ACM-AITP-CoursePro#17]
As a **developer** I need a designated class for a Assignment in CoursePro. The `Assignment` class will be a child of the Event class (see #15), and will hold the following fields:
* A List of assignment files (`File` objects, which will be saved in the local storage)
* Grade (A `double`  value)
* A List of `Note` objects (consider ArrayList or LinkedList)

## Definition of Done:

The `Assignment` class exists with the specifications listed above (or modified functionality discussed in subsequent comments below).

## Acceptance Criteria:

The application can be started as before, and the `Assignment` class has no compilation errors and passes all developer-defined unit tests, which provide full line coverage for the `Assignment` class' methods.

**Comment by wpmoore2** [comment]
Left from java implementation - maybe valid later but closing for now
