### ISSUE TITLE
Create Location

### ISSUE THREAD

**Issue by mattgd** [ACM-NCSU/ACM-AITP-CoursePro#18]
As a **developer** I need a designated class for a Location in CoursePro. The `Location` class will hold the following fields:
* Name (A `String` that cannot be null or empty)
* Description (A `String`)
* Address (A `String`)

The Location class will primarily be used for Events (#15).

## Definition of Done:

The `Location` class exists with the specifications listed above (or modified functionality discussed in subsequent comments below), and can be used in other classes.

## Acceptance Criteria:

The application can be started as before, and the `Location` class has no compilation errors and passes all developer-defined unit tests, which provide full line coverage for the `Location` class' methods.

**Comment by wpmoore2** [comment]
From old java implementation. May revisit this later
