### ISSUE TITLE
GOOD START (beginner): Show workspace name on Home page

### ISSUE THREAD

**Issue by wpmoore2** [ACM-NCSU/ACM-AITP-CoursePro#24]
The home page is loaded with a very basic welcome message.  The workspace selected (or assumed from being the "last_used") should be displayed somewhere the user is sure that they are operating in their space.

This could be a chance to improve the welcome message. However, how the workspace name is displayed is up to who ever is implementing this (though it will be reviewed).

Once the home page displays the correct workspace, volia all done!

**Comment by anastasiaeg** [comment]
I got it to work but I kinda suck at design, do you have any wireframes of what you want the application to look like?

**Comment by wpmoore2** [comment]
Thank @anastasiaeg! We appreciate the contribution, and are happy to have the feature!
